name: aimi_lib
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
resolution: workspace

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  dio: ^5.9.0
  html: ^0.15.6
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
